### ISSUE TITLE
Fix the Code Snippets in the RESTful Documentation

### ISSUE THREAD

**Issue by stuarthoye** [CMPUT404F16/cmput404-project#1]
Work has been started on generating a RESTful documentation for the project. The entries are based off of a template, which has an example of the code that would be used for the example documentation. The code in the existing entries is still generic, and needs to be updated to reflect the actual implementation that will be present in our project.

**Comment by NJJ-UA** [comment]
I have finished most part of the implementation of api, and you can take a look
